project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FDA
  pod 'IQKeyboardManagerSwift'
  pod 'SlideMenuControllerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'CryptoSwift', '~> 0.7.1'
  pod 'ActionSheetPicker-3.0'
  
  target 'HPHCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HPHCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
