project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FDA
  pod 'IQKeyboardManagerSwift'
  pod 'SlideMenuControllerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'CryptoSwift'
  pod 'ActionSheetPicker-3.0'
  
end

